In [25]:
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [26]:
data = pd.read_csv('csv_result-test_50.csv')

In [33]:
X = data.iloc[ :, 1:-1].values
Y=  data.iloc[:, -1].values

In [41]:
model = ExtraTreesClassifier(n_estimators=100)

In [42]:
model.fit(X, Y)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [36]:
print(model.feature_importances_)

[0.008 0.006 0.008 0.064 0.061 0.056 0.118 0.063 0.015 0.023 0.039 0.029
 0.006 0.012 0.007 0.032 0.11  0.069 0.006 0.005 0.007 0.017 0.008 0.019
 0.014 0.01  0.01  0.029 0.018 0.04  0.024 0.015 0.02  0.011 0.01  0.01 ]


In [40]:
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)
print(fit.scores_)
features = fit.transform(X)
set_printoptions(precision=3)
print(features[0:5,:])

[9.511e-01 4.906e-01 2.419e-01 9.086e+02 4.317e+03 4.023e+03 8.212e+02
 2.736e+03 1.199e+03 1.119e+03 1.610e+03 1.269e+03 2.091e+02 7.594e+02
 4.912e+02 1.125e+03 9.369e+03 7.050e+03 9.091e-02 1.722e-02 1.862e-01
 1.643e+03 8.064e+02 5.421e+02 1.178e+03 5.497e+02 7.514e+02 1.935e+03
 1.350e+03 1.218e+03 1.040e+03 4.964e+02 5.553e+02 2.901e+00 2.363e+01
 3.828e+01]
[[  0.049  -8.91   -1.986 -10.003]
 [  0.288  -9.087  -0.554 -10.013]
 [  1.382  -9.44   -0.565 -10.12 ]
 [ -0.188  -9.805  -0.371  -9.966]
 [ -0.319  -9.957  -0.407 -10.024]]
